from django.urls import path
from django.contrib.auth.views import LogoutView # Добавили импорт
from . import views

urlpatterns = [
    path("", views.home, name="home"),
    path("login/", views.UserLoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("dispatch/", views.dispatch_user, name="dispatch_user"),
    path("manager/", views.manager_dashboard, name="manager_dashboard"),
    path("finance/", views.finance_dashboard, name="finance_dashboard"),
    path("warehouses/", views.warehouse_list, name="warehouse_list"),
    path("warehouses/add/", views.warehouse_add, name="warehouse_add"),
    path("warehouses/<int:pk>/", views.warehouse_detail, name="warehouse_detail"),
    path("warehouses/<int:pk>/edit/", views.warehouse_edit, name="warehouse_edit"),
    path("warehouses/materials/", views.material_list, name="material_list"),
    path("warehouses/materials/add/", views.material_add, name="material_add"),
    path("warehouses/materials/<int:pk>/edit/", views.material_edit, name="material_edit"),
    path("warehouses/materials/<int:pk>/delete/", views.material_delete, name="material_delete"),
    path("finance/material/quick-add/", views.finance_quick_material, name="finance_quick_material"),
    path("finance/purchases/", views.purchase_request_list, name="purchase_request_list"),
    path("finance/purchases/new/", views.purchase_request_create, name="purchase_request_create"),
    path("finance/purchases/<int:pk>/", views.purchase_request_edit, name="purchase_request_edit"),
    path("finance/purchase/<int:pk>/status/", views.finance_update_purchase_status, name="finance_update_purchase_status"),
    path("finance/estimate/<int:pk>/export/pdf/", views.export_estimate_pdf, name="export_estimate_pdf"),
    path("finance/estimate/<int:pk>/export/docx/", views.export_estimate_docx, name="export_estimate_docx"),
    path("projects/<int:project_id>/estimates/add/", views.create_estimate, name="create_estimate"),
    path("site/", views.site_manager_dashboard, name="site_manager_dashboard"),
    path("projects/", views.project_list, name="project_list"),
    path("projects/<int:pk>/", views.project_detail, name="project_detail"),
    path("projects/<int:pk>/edit/", views.edit_project, name="edit_project"),
    path("projects/add/", views.add_project, name="add_project"),
    path("finance/estimate/<int:pk>/", views.estimate_detail, name="estimate_detail"),
    path("brigades/add/", views.brigade_add, name="brigade_add"),
    path("brigades/<int:pk>/edit/", views.brigade_edit, name="brigade_edit"),
    path("workers/", views.worker_list, name="worker_list"),
    path("workers/add/", views.add_worker, name="add_worker"),
    path("workers/edit/<int:pk>/", views.edit_worker, name="edit_worker"),
    path("workers/delete/<int:pk>/", views.delete_worker, name="delete_worker"),
    path("technique/", views.technique_list, name="technique_list"),
    path("technique/add/", views.add_technique, name="add_technique"),
    path("technique/edit/<int:pk>/", views.edit_technique, name="edit_technique"),
    path("tasks/add/<int:project_id>/", views.add_task, name="add_task"),
    path("tasks/update_status/<int:pk>/", views.update_task_status, name="update_task_status"),
    path("api/funnel/", views.api_funnel, name="api_funnel"),
    path("api/projects/<int:project_id>/interactions/", views.api_add_interaction, name="api_add_interaction"),
    path("api/estimates/<int:estimate_id>/recalc/", views.api_recalc_estimate, name="api_recalc_estimate"),
    path("api/material-prices/", views.api_material_prices, name="api_material_prices"),
    path("api/gantt/", views.api_gantt, name="api_gantt"),
    path(
        "api/estimates/<int:estimate_id>/purchase-request/",
        views.api_create_purchase_request,
        name="api_create_purchase_request",
    ),
    path("api/monitoring/summary/", views.api_monitoring_summary, name="api_monitoring_summary"),
    path(
        "api/estimates/<int:estimate_id>/document/",
        views.api_generate_estimate_document,
        name="api_generate_estimate_document",
    ),
    path("api/estimates/<int:estimate_id>/export/pdf/", views.api_export_estimate_pdf, name="api_export_estimate_pdf"),
    path("api/estimates/<int:estimate_id>/export/docx/", views.api_export_estimate_docx, name="api_export_estimate_docx"),
    path("api/projects/", views.api_projects, name="api_projects"),
    path("api/projects/create/", views.api_projects_create, name="api_projects_create"),
    path("api/projects/<int:project_id>/update/", views.api_projects_update, name="api_projects_update"),
    path("api/projects/<int:project_id>/delete/", views.api_projects_delete, name="api_projects_delete"),
    path("api/estimates/", views.api_estimates, name="api_estimates"),
    path("api/materials/", views.api_materials, name="api_materials"),
    path("api/materials/create/", views.api_materials_create, name="api_materials_create"),
    path("api/materials/<int:material_id>/update/", views.api_materials_update, name="api_materials_update"),
    path("api/materials/<int:material_id>/delete/", views.api_materials_delete, name="api_materials_delete"),
    path("api/tasks/", views.api_tasks, name="api_tasks"),
    path("api/warehouses/", views.api_warehouses, name="api_warehouses"),
    path("api/purchase-requests/", views.api_purchase_requests, name="api_purchase_requests"),
]